
name: 'Bump'
description: 'Bump the manifest and generate changelogs'
inputs:
  bump-to:
    description: 'semver version to bump to'
    required: true
  package:
    description: 'in a monorepo, package that contains the files to be bumped ie. app-opine -> packages/app-opine'
    required: false
    default: ''
  prefix:
    description: 'string to use as the tag prefix ie. hyper-app-opine -> hyper-app-opine@v1.2.3. Defaults to the input for package'
    required: false
    default: ''
  runtime:
    description: 'runtime for project node or deno. default: deno'
    required: false
    default: deno
outputs:
  version:
    description: 'The semver version bumped to'
  tag:
    description: 'The git tag created'
runs:
  using: 'node12'
  main: 'dist/index.js'
