name: ⬆️ Test and Deploy Hyper CI Bump

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
    # See https://github.com/hyper63/hyper-ci-bump#inputs for available inputs for the bump action
      version:
        description: the semver version to bump to
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Download deps
        run: npm i

      - name: ⚡ Run Tests
        run: npm test
        env:
          CI: true

  release:
    needs: [test]
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    concurrency:
      group: release
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          # Allows for pushes from this workflow to trigger subsequent workflows 
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: 🤓 Set Git User
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: ✊ Bump
        id: bump
        uses: hyper63/hyper-ci-bump@main
        with:
          bump-to: ${{ github.event.inputs.version }}

      - name: ⬆️ Push
        run: |
          git push --follow-tags

      - name: 🤖 Create Github Release
        if: steps.bump.outputs.tag
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
